In [1]:
# Importing necessary libraries

import nltk
from nltk.corpus import stopwords
import re
from tqdm.notebook import tqdm
import time
import requests
import random

In [2]:
# Taking example text sample:
text = " J. Walk @Jwalk35_ 18h I read the article. He essentially said that instead of trying to fit a  \
       woman into this role, they should write an original character better than james bond for a woman."

text2 = "Joe Lara- the star of the famous adventure movie 'Tarzan: The Epic Adventures' has passed away in a plane crash. \
        The 58-year-old was with his wife"       

In [3]:
def Cleaning(text):
  def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext


  def replaceUrls(data):
      #Removing URLs with a regular expression
      url_pattern = re.compile(r'https?://\S+|www\.\S+')
      data = url_pattern.sub(r'', data)
      return data

  def removeEmail(data):
      # Remove Emails
      data = re.sub('\S*@\S*\s?', '', data)
      return data

  def misc(data):
      # Remove new line characters
      data = re.sub(r'\.+', ".", data)
      data = re.sub('\s+', ' ', data)
      # Remove distracting single quotes
      data = re.sub("\'", "", data)
      return data

  sentence = cleanhtml(text)
  sentence = replaceUrls(sentence)
  sentence = removeEmail(sentence)
  sentence = misc(sentence)
  sentence = re.sub(r'[^a-zA-Z]', ' ', sentence)
  sentence = re.sub(' +', ' ', sentence)
  sentence = sentence.lower()

  return sentence

In [4]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sadpa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
stopwords_list = stopwords.words('english')

def removeStopwords(sentence):  
  words = sentence.split(" ")
  filtered_sentence = [word for word in words if not word in stopwords_list]
  ans = ' '.join([ i for i in filtered_sentence if len(i) >= 2])

  return ans

In [6]:
pre_final = Cleaning(text)
print(pre_final)
pre_final = removeStopwords(pre_final)
print(pre_final)

 j walk h i read the article he essentially said that instead of trying to fit a woman into this role they should write an original character better than james bond for a woman 
walk read article essentially said instead trying fit woman role write original character better james bond woman


In [7]:
pre_final2 = Cleaning(text2)
print(pre_final2)
pre_final2 = removeStopwords(pre_final2)
print(pre_final2)

joe lara the star of the famous adventure movie tarzan the epic adventures has passed away in a plane crash the year old was with his wife
joe lara star famous adventure movie tarzan epic adventures passed away plane crash year old wife


In [10]:
import pandas as pd
import pickle


# This file has the information on every common word and its embeddings.
save_data = open(r"word_embeddings_model1.pickle", "rb")
word_embed = pickle.load(save_data)
save_data.close()

In [15]:
word_embed

In [16]:
# Creating text vectors
import numpy as np

count = 0
document_embeddings = np.zeros(50, dtype=float)
try:
  for word in pre_final.split(" "):
    array = np.asarray(word_embed[word], dtype=float)
    document_embeddings = np.add(document_embeddings, array, out=document_embeddings, casting="unsafe")
except:
  count = count + 1

print("Number of words in text 1:", len(pre_final.split(" ")))
print("Unrecognizable word count in text 1:", count)

Number of words in text 1: 17
Unrecognizable word count in text 1: 1


In [17]:
count2 = 0
document_embeddings2 = np.zeros(50, dtype=float)
try:
  for word in pre_final2.split(" "):
    array = np.asarray(word_embed[word], dtype=float)
    document_embeddings2 = np.add(document_embeddings2, array, out=document_embeddings2, casting="unsafe")
except:
  count2 = count2 + 1

print("Number of words in text 1:", len(pre_final2.split(" ")))
print("Unrecognizable word count in text 1:", count2)

Number of words in text 1: 16
Unrecognizable word count in text 1: 1


In [18]:
document_embeddings

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
document_embedding = np.concatenate([document_embeddings, document_embeddings])
document_embedding

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
document_embeddings2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
document_embedding2 = np.concatenate([document_embeddings2, document_embeddings2])
document_embedding2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# We will go for cosine_similarity
def cosine_similarity(A, B):
    """
    Input:
        A: a numpy array which corresponds to a word vector
        B: A numpy array which corresponds to a word vector
    Output:
        cos: numerical number representing the cosine similarity between A and B.
    """
    dot = np.dot(A, B)
    norma = np.sqrt(np.dot(A, A))
    normb = np.sqrt(np.dot(B, B))
    cos = dot / (norma * normb)

    return cos

In [23]:
similarity = cosine_similarity(document_embeddings, document_embeddings2)
print(similarity)

nan


C:\Users\sadpa\AppData\Local\Temp\ipykernel_17044\2338355024.py:13: RuntimeWarning: invalid value encountered in double_scalars
  cos = dot / (norma * normb)


In [24]:
similarity_new = cosine_similarity(document_embedding, document_embedding2)
print(similarity_new)

nan


C:\Users\sadpa\AppData\Local\Temp\ipykernel_17044\2338355024.py:13: RuntimeWarning: invalid value encountered in double_scalars
  cos = dot / (norma * normb)
