In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Importing necessary libraries

import nltk
from nltk.corpus import stopwords
import re
from tqdm.notebook import tqdm
import time
import requests
import random

In [ ]:
# Taking example text sample:
text = " J. Walk @Jwalk35_ 18h I read the article. He essentially said that instead of trying to fit a  \
       woman into this role, they should write an original character better than james bond for a woman."

text2 = "Joe Lara- the star of the famous adventure movie 'Tarzan: The Epic Adventures' has passed away in a plane crash. \
        The 58-year-old was with his wife"       

In [ ]:
def Cleaning(text):
  def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext


  def replaceUrls(data):
      #Removing URLs with a regular expression
      url_pattern = re.compile(r'https?://\S+|www\.\S+')
      data = url_pattern.sub(r'', data)
      return data

  def removeEmail(data):
      # Remove Emails
      data = re.sub('\S*@\S*\s?', '', data)
      return data

  def misc(data):
      # Remove new line characters
      data = re.sub(r'\.+', ".", data)
      data = re.sub('\s+', ' ', data)
      # Remove distracting single quotes
      data = re.sub("\'", "", data)
      return data

  sentence = cleanhtml(text)
  sentence = replaceUrls(sentence)
  sentence = removeEmail(sentence)
  sentence = misc(sentence)
  sentence = re.sub(r'[^a-zA-Z]', ' ', sentence)
  sentence = re.sub(' +', ' ', sentence)
  sentence = sentence.lower()

  return sentence

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stopwords_list = stopwords.words('english')
def removeStopwords(sentence):  
  words = sentence.split(" ")
  filtered_sentence = [word for word in words if not word in stopwords_list]
  ans = ' '.join([ i for i in filtered_sentence if len(i) >= 2])

  return ans

In [ ]:
pre_final = Cleaning(text)
print(pre_final)
pre_final = removeStopwords(pre_final)
print(pre_final)

 j walk h i read the article he essentially said that instead of trying to fit a woman into this role they should write an original character better than james bond for a woman 
walk read article essentially said instead trying fit woman role write original character better james bond woman


In [ ]:
pre_final2 = Cleaning(text2)
print(pre_final2)
pre_final2 = removeStopwords(pre_final2)
print(pre_final2)

joe lara the star of the famous adventure movie tarzan the epic adventures has passed away in a plane crash the year old was with his wife
joe lara star famous adventure movie tarzan epic adventures passed away plane crash year old wife


In [ ]:
import pandas as pd

# This file has the information on every common word and its embeddings.
save_data = open(r"drive/MyDrive/Dataset/Models/word_embeddings_model1.pickle", "rb")
word_embed = pickle.load(save_data)
save_data.close()

In [ ]:
word_embed['the']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([ 0.08972839, -0.4026127 , -0.2109241 , -0.18708473, -0.21843027,
       -0.22599791,  0.33714572, -0.25546554,  0.3098281 ,  0.06694622,
       -0.6033739 ,  0.34739166,  0.21200591,  0.2837941 , -0.2552652 ,
        0.278658  ,  0.00732607,  0.5215177 ,  0.23229359, -0.01886191,
        0.11897848, -0.07872345,  0.31105882, -0.27565423,  0.6222356 ,
        0.39243025,  0.6641766 ,  0.7036882 , -0.17577358, -0.19602324,
        0.42333782, -0.2801832 , -0.04348856, -0.37758586,  0.4080701 ,
       -0.05026684,  0.253955  ,  0.20047438, -0.5026844 , -0.00139159,
       -0.23464508,  0.16398458,  0.37383717, -0.6876745 ,  0.07311639,
       -0.14231576,  0.15746595, -0.12399933, -0.06738635, -0.05721248],
      dtype=float32)

In [ ]:
# Creating text vectors
import numpy as np

count = 0
document_embeddings = np.zeros(50, dtype=float)
try:
  for word in pre_final.split(" "):
    array = np.asarray(word_embed[word], dtype=float)
    document_embeddings = np.add(document_embeddings, array, out=document_embeddings, casting="unsafe")
except:
  count = count + 1

print("Number of words in text 1:", len(pre_final.split(" ")))
print("Unrecognizable word count in text 1:", count)

Number of words in text 1: 17
Unrecognizable word count in text 1: 0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [ ]:
count2 = 0
document_embeddings2 = np.zeros(50, dtype=float)
try:
  for word in pre_final2.split(" "):
    array = np.asarray(word_embed[word], dtype=float)
    document_embeddings2 = np.add(document_embeddings2, array, out=document_embeddings2, casting="unsafe")
except:
  count2 = count2 + 1

print("Number of words in text 1:", len(pre_final2.split(" ")))
print("Unrecognizable word count in text 1:", count2)

Number of words in text 1: 16
Unrecognizable word count in text 1: 0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """


In [ ]:
document_embeddings

array([  1.32788581, -15.26545109,   4.74076638,   0.92330539,
         0.24664982,  -1.11875891,  12.61647896,  -4.4750995 ,
         7.48472095,   0.72582556, -12.71821474,   8.29372767,
         7.60167133,  14.38859514,  -6.06242028,   2.13325731,
        -4.70008556,  16.03036302,   2.91728007,  -1.31353339,
         0.74579782,   3.89921119,  10.60212768,  -8.58539575,
         5.65275766,   1.92925315,  19.4137764 ,  13.47097754,
        -0.35150574,   0.23039759,   5.1079847 ,  -0.72054015,
        -0.52674526,   2.10636102,   6.06609742,  -5.05324206,
         2.80899958,   7.8283454 , -10.64413992,   4.02219872,
        -9.35408118,  10.04498111,   7.65632325,  -6.87888258,
         1.96061099,  -2.14515963,   3.14180244,  -0.75051255,
        -4.1844725 ,  -3.56054363])

In [ ]:
document_embedding = np.concatenate([document_embeddings, document_embeddings])
document_embedding

array([  1.32788581, -15.26545109,   4.74076638,   0.92330539,
         0.24664982,  -1.11875891,  12.61647896,  -4.4750995 ,
         7.48472095,   0.72582556, -12.71821474,   8.29372767,
         7.60167133,  14.38859514,  -6.06242028,   2.13325731,
        -4.70008556,  16.03036302,   2.91728007,  -1.31353339,
         0.74579782,   3.89921119,  10.60212768,  -8.58539575,
         5.65275766,   1.92925315,  19.4137764 ,  13.47097754,
        -0.35150574,   0.23039759,   5.1079847 ,  -0.72054015,
        -0.52674526,   2.10636102,   6.06609742,  -5.05324206,
         2.80899958,   7.8283454 , -10.64413992,   4.02219872,
        -9.35408118,  10.04498111,   7.65632325,  -6.87888258,
         1.96061099,  -2.14515963,   3.14180244,  -0.75051255,
        -4.1844725 ,  -3.56054363,   1.32788581, -15.26545109,
         4.74076638,   0.92330539,   0.24664982,  -1.11875891,
        12.61647896,  -4.4750995 ,   7.48472095,   0.72582556,
       -12.71821474,   8.29372767,   7.60167133,  14.38

In [ ]:
document_embeddings2

array([  0.46074164,  -9.81032007,   2.35423303,   1.36082375,
        -1.04345066,  -6.49139996,   7.5316624 ,  -9.06855639,
        10.42076805,  -8.60723971, -10.91328533,   4.53859866,
         6.80766531,   4.01298152,   1.35811688,   3.10402097,
         2.13877971,  14.61606732,   1.1612465 ,  -1.67852069,
         3.43584716,   4.13053974,   5.53641322,  -5.95889189,
         5.14441624,   0.36780485,  17.29011382,  14.95904548,
         4.32079427,   1.84643187,   3.62155507,  -4.48962826,
        -1.31869532,  -4.7503546 ,   2.1698935 ,  -2.26030859,
         7.63799253,   5.04382198,  -5.02412524,  -1.35123321,
        -7.74225397,   0.96739344,   1.45822214, -12.01656985,
         5.4329111 ,  -3.49751539,   1.38893725,   2.77415944,
         3.17049427,  -5.48010895])

In [ ]:
document_embedding2 = np.concatenate([document_embeddings2, document_embeddings2])
document_embedding2

array([  0.46074164,  -9.81032007,   2.35423303,   1.36082375,
        -1.04345066,  -6.49139996,   7.5316624 ,  -9.06855639,
        10.42076805,  -8.60723971, -10.91328533,   4.53859866,
         6.80766531,   4.01298152,   1.35811688,   3.10402097,
         2.13877971,  14.61606732,   1.1612465 ,  -1.67852069,
         3.43584716,   4.13053974,   5.53641322,  -5.95889189,
         5.14441624,   0.36780485,  17.29011382,  14.95904548,
         4.32079427,   1.84643187,   3.62155507,  -4.48962826,
        -1.31869532,  -4.7503546 ,   2.1698935 ,  -2.26030859,
         7.63799253,   5.04382198,  -5.02412524,  -1.35123321,
        -7.74225397,   0.96739344,   1.45822214, -12.01656985,
         5.4329111 ,  -3.49751539,   1.38893725,   2.77415944,
         3.17049427,  -5.48010895,   0.46074164,  -9.81032007,
         2.35423303,   1.36082375,  -1.04345066,  -6.49139996,
         7.5316624 ,  -9.06855639,  10.42076805,  -8.60723971,
       -10.91328533,   4.53859866,   6.80766531,   4.01

In [ ]:
# We will go for cosine_similarity
def cosine_similarity(A, B):
    """
    Input:
        A: a numpy array which corresponds to a word vector
        B: A numpy array which corresponds to a word vector
    Output:
        cos: numerical number representing the cosine similarity between A and B.
    """
    dot = np.dot(A, B)
    norma = np.sqrt(np.dot(A, A))
    normb = np.sqrt(np.dot(B, B))
    cos = dot / (norma * normb)

    return cos

In [ ]:
similarity = cosine_similarity(document_embeddings, document_embeddings2)
print(similarity)

0.8145993975669695


In [ ]:
similarity_new = cosine_similarity(document_embedding, document_embedding2)
print(similarity_new)

0.8145993975669695
