In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('fake_job_postings.csv')
df1.head()

job_id                                      title            location  \
0       1                           Marketing Intern    US, NY, New York   
1       2  Customer Service - Cloud Video Production      NZ, , Auckland   
2       3    Commissioning Machinery Assistant (CMA)       US, IA, Wever   
3       4          Account Executive - Washington DC  US, DC, Washington   
4       5                        Bill Review Manager  US, FL, Fort Worth   

  department salary_range                                    company_profile  \
0  Marketing          NaN  We're Food52, and we've created a groundbreaki...   
1    Success          NaN  90 Seconds, the worlds Cloud Video Production ...   
2        NaN          NaN  Valor Services provides Workforce Solutions th...   
3      Sales          NaN  Our passion for improving quality of life thro...   
4        NaN          NaN  SpotSource Solutions LLC is a Global Human Cap...   

                                         description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  \
0  Experience with content management systems a m...   
1  What we expect from you:Your key responsibilit...   
2  Implement pre-commissioning and commissioning ...   
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...   
4  QUALIFICATIONS:RN license in the State of Texa...   

                                            benefits  telecommuting  \
0                                                NaN              0   
1  What you will get from usThrough being part of...              0   
2                                                NaN              0   
3  Our culture is anything but corporate—we have ...              0   
4                              Full Benefits Offered              0   

   has_company_logo  has_questions employment_type required_experience  \
0                 1              0           Other          Internship   
1                 1              0       Full-time      Not Applicable   
2                 1              0             NaN                 NaN   
3                 1              0       Full-time    Mid-Senior level   
4                 1              1       Full-time    Mid-Senior level   

  required_education                   industry              function  \
0                NaN                        NaN             Marketing   
1                NaN  Marketing and Advertising      Customer Service   
2                NaN                        NaN                   NaN   
3  Bachelor's Degree          Computer Software                 Sales   
4  Bachelor's Degree     Hospital & Health Care  Health Care Provider   

   fraudulent  
0           0  
1           0  
2           0  
3           0  
4           0

In [3]:
df1.shape

(17880, 18)

In [4]:
df=df1[['description','requirements','fraudulent']]
df.head()

description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  fraudulent  
0  Experience with content management systems a m...           0  
1  What we expect from you:Your key responsibilit...           0  
2  Implement pre-commissioning and commissioning ...           0  
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...           0  
4  QUALIFICATIONS:RN license in the State of Texa...           0

In [5]:
###Drop Nan Values
df=df.dropna()

In [6]:
df.shape

(15185, 3)

In [7]:
## Get the Independent Features

X=df.drop('fraudulent',axis=1)

In [8]:
## Get the Dependent features
y=df['fraudulent']

In [9]:
y.value_counts()

0    14473
1      712
Name: fraudulent, dtype: int64

In [10]:
import tensorflow as tf
tf.__version__

'2.8.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [12]:
voc_size=5000

## Onehot Representation:

In [13]:
message = X.copy()

In [14]:
message['description'][1]

"Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you!\xa0We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious about\xa0delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. \xa0Therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 Seconds, the worlds Cloud Video Production Service -\xa0http://90

In [15]:
message.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [18]:
corpus[1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http url fbe afac cd c f b eef e e f ca dd second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product suc

In [19]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[1]

[2690,
 1283,
 3731,
 190,
 3300,
 1134,
 1714,
 4415,
 4614,
 1160,
 1492,
 2876,
 3709,
 1095,
 1601,
 1443,
 1409,
 796,
 4294,
 4076,
 27,
 3547,
 2580,
 3882,
 1714,
 2131,
 872,
 3745,
 1353,
 2481,
 3366,
 2812,
 540,
 3685,
 2290,
 3882,
 3177,
 1134,
 1714,
 4098,
 555,
 1965,
 4896,
 882,
 4657,
 3709,
 3709,
 449,
 4381,
 2580,
 4657,
 3709,
 4631,
 3961,
 703,
 3882,
 4112,
 3743,
 728,
 2458,
 1530,
 1049,
 2648,
 2617,
 4027,
 4680,
 1826,
 3172,
 3646,
 4282,
 2206,
 2491,
 1965,
 2463,
 4643,
 1158,
 1835,
 94,
 4751,
 3924,
 2547,
 3628,
 3646,
 1965,
 2547,
 2224,
 1208,
 3685,
 3547,
 2580,
 3882,
 1714,
 1945,
 3501,
 1626,
 4964,
 3160,
 740,
 4906,
 218,
 977,
 2298,
 2298,
 4906,
 271,
 2972,
 1208,
 3685,
 3547,
 2580,
 3882,
 1714,
 1733,
 2458,
 3110,
 4671,
 2770,
 165,
 4954,
 2580,
 420,
 233,
 4792,
 891,
 3685,
 4678,
 2340,
 3709,
 1189,
 3547,
 3030,
 2864,
 1208,
 4433,
 1466,
 1580,
 2635,
 684,
 2182,
 3743,
 3608,
 2580,
 3882,
 1883,
 3709,
 1435,


## Embedding Representation:

In [20]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4822  420 3709 ... 4725  161 4246]
 [ 449 2275 2895 ... 1369 2783 1820]
 [   0    0    0 ... 3335   92  724]
 ...
 [4606 4212 3390 ... 3965 1098 1673]
 [ 101 4584 3854 ...  950 1158 4657]
 [1882 3527  943 ... 3290 4525 4292]]


In [21]:
embedded_docs[0]

array([4822,  420, 3709,  619, 3205, 4149, 2157, 2146, 4063, 1576, 2473,
       2473, 4063, 4498, 1628, 3169, 4063, 4718, 4063, 2856, 2066, 1492,
        542,  373, 3558, 1601, 3743,  470,  586, 3195, 3450, 3656, 2748,
       2855,  637,  594, 4325, 4725,  161, 4246])

In [22]:
## Creating model
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100))) ##Just add bidirectional!!, except it would just behave as normal LSTM Model
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 50)            250000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              120800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 371,001
Trainable params: 371,001
Non-trainable params: 0
_________________________________________________________________
None


In [23]:
len(embedded_docs),y.shape

(15185, (15185,))

In [24]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [25]:
X_final[1]

array([ 449, 2275, 2895, 4225, 4241, 4400,  582, 1208, 4792,  320, 2580,
       4342, 2648, 2458, 4652, 3685, 4443, 4652, 3189, 2397,  127, 3907,
       4737, 3558, 2035, 4413, 1244, 2798, 1492, 1253, 2035, 3558, 1777,
       2547, 2861, 2440, 3506, 1369, 2783, 1820])

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25, random_state=32)

In [27]:
model1.fit(X_train,y_train,
           validation_data=(X_test,y_test),
           epochs=12,
           batch_size=64)

Epoch 1/12
178/178 [==============================] - 8s 34ms/step - loss: 0.1742 - accuracy: 0.9607 - val_loss: 0.1449 - val_accuracy: 0.9579
Epoch 2/12
178/178 [==============================] - 5s 31ms/step - loss: 0.0792 - accuracy: 0.9767 - val_loss: 0.1703 - val_accuracy: 0.9618
Epoch 3/12
178/178 [==============================] - 6s 32ms/step - loss: 0.0515 - accuracy: 0.9859 - val_loss: 0.1618 - val_accuracy: 0.9637
Epoch 4/12
178/178 [==============================] - 6s 32ms/step - loss: 0.0441 - accuracy: 0.9870 - val_loss: 0.1795 - val_accuracy: 0.9608
Epoch 5/12
178/178 [==============================] - 6s 33ms/step - loss: 0.0265 - accuracy: 0.9924 - val_loss: 0.2083 - val_accuracy: 0.9629
Epoch 6/12
178/178 [==============================] - 6s 32ms/step - loss: 0.0204 - accuracy: 0.9946 - val_loss: 0.1711 - val_accuracy: 0.9634
Epoch 7/12
178/178 [==============================] - 6s 32ms/step - loss: 0.0148 - accuracy: 0.9959 - val_loss: 0.1873 - val_accuracy: 0.9673

## Model Performance and Accuracy:

In [31]:
y_pred=model1.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3585,    0],
       [ 212,    0]], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9441664471951541

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      3585
           1       0.00      0.00      0.00       212

    accuracy                           0.94      3797
   macro avg       0.47      0.50      0.49      3797
weighted avg       0.89      0.94      0.92      3797



C:\Users\sadpa\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sadpa\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sadpa\miniconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
